### PR TITLE
Improve README.md

### PR DESCRIPTION
**Pull request by manaswinidas**
Fix broken links

### CODE REVIEW

**Review by hantsy — APPROVED** [review]

**Comment by hantsy** [comment]
@manaswinidas Thanks for correcting the typo issues.

**Comment by manaswinidas** [comment]
@hantsy my pleasure, can you help me with the build and run instructions for the GraphQL client? I'm getting error while I'm trying to build it.

**Comment by hantsy** [comment]
@manaswinidas The *type safe* client API is not so stable currently there may be some changes, try to update yourself.

**Comment by hantsy** [comment]
@manaswinidas  Fixed the graphql client example.

**Comment by manaswinidas** [comment]
@hantsy I'm getting the following error while trying to `mvn clean install` : ` Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project quarkus-examples-graphql-client: Fatal error compiling: error: release version 17 not supported` or can you point me to the build and run instructions for `graphql-client`

**Pull request merged**
